# Generated by Django 3.1.14 on 2025-01-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20250129_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Appeared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Disappeared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
