# Generated by Django 3.1.14 on 2025-02-01 07:47

from django.db import migrations, models

def replace_null_with_empty_string(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')  # Имя приложения и модели
    Pokemon.objects.filter(title_en__isnull=True).update(title_en='')
    Pokemon.objects.filter(title_jp__isnull=True).update(title_jp='')
    Pokemon.objects.filter(description__isnull=True).update(description='')

class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20250129_1928'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty_string),  # Добавляем замену NULL на ''
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название покемона на английском'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название покемона на японском'),
        ),
    ]
